services:
  postgres:
    image: 'postgres:latest'
    container_name: arena-postgres
    environment:
      - 'POSTGRES_DB=arena-db'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '25432:5432'
  redis:
    image: redis:latest
    container_name: arena-redis
    ports:
      - '26379:6379'
    env_file:
      - .env