spring:
  application:
    name: arena
  datasource:
    url: jdbc:postgresql://arena-postgres:5432/arena-db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
  redis:
    host: arena-redis
    port: 6379
    database: 0
  profiles:
    include:
      - oauth2
  cache:
    redis:
      time-to-live: 30m
server:
  port: 9000
  servlet:
    session:
      cookie:
        same-site: none
        secure: true